Train:
    batch_size: 512
    learning_rate: 0.0001
    attack_lr: 0.005
    num_epochs: 100
    warmup: 10
    gpuid: '0'
    surrogate_name: FEDformer
    model_name: Autoformer
    dataset: Weather
    trigger_name : TgrGCN
    pattern_type: cone
    delta: 0
    trigger_len: 4
    pattern_len: 7
    bef_tgr_len: 6
    lam_norm: 0.5 #0.05 useless
    alpha_s: 0.3  # spatial_poison_rate
    alpha_t: 0.03  # temporal_poison_rate
    epsilon: 0.2
    hidden_dim: 64  # hidden_dim for the trigger generator
